# Generated by Django 5.1 on 2025-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_remove_item_expiring_date_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
    ]
