# Generated by Django 5.1 on 2025-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
