# Generated by Django 5.1 on 2025-11-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_options_remove_invoice_contact_number_and_more'),
        ('store', '0002_color_remove_item_expiring_date_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='store.item'),
        ),
    ]
