# Generated by Django 5.1 on 2025-11-19 09:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoiceitem_color_invoiceitem_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Shipping and Handling'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (e.g. 10 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price Per Item (Rs)'),
        ),
    ]
