# Generated by Django 5.1 on 2025-11-21 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_shipping_alter_invoiceitem_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Discount (%)'),
        ),
    ]
