# Generated by Django 5.1 on 2025-12-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoiceitem_custom_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='color',
        ),
    ]
