# Generated by Django 5.1 on 2026-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment_created_by_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
