# Generated by Django 5.1 on 2026-03-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_last_updated_at_payment_last_updated_at'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='locations.store'),
        ),
    ]
