# Generated by Django 5.1 on 2025-11-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_remove_item_expiring_date_productvariant'),
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='store.item'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_details', to='store.item'),
        ),
    ]
