# Generated by Django 5.1 on 2025-12-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_remove_item_expiring_date_productvariant'),
        ('transactions', '0005_alter_purchase_item_alter_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_detail_colors', to='store.color'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=1),
        ),
    ]
