# Generated by Django 5.1 on 2026-02-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_purchase_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='slug',
        ),
        migrations.AddField(
            model_name='purchase',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
