# Generated by Django 5.1 on 2026-02-06 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_purchase_slug_purchase_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
