# Generated by Django 5.1 on 2025-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_purchase_item_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='S', max_length=1),
        ),
    ]
