# Generated by Django 5.1 on 2026-02-06 19:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_payment_created_by_alter_payment_date_and_more'),
        ('store', '0005_remove_item_serial_item_stock_alter_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date (e.g., 2022/11/22)')),
                ('shipping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Shipping and Handling')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total Amount (Rs)')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Grand Total (Rs)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price Per Item (Rs)')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Discount (%)')),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='store.item')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='invoice_inv_date_6c372c_idx'),
        ),
    ]
