# Generated by Django 5.1 on 2026-03-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_last_updated_at_alter_invoice_date'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='locations.store'),
        ),
    ]
